apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: aws-iam-example-k8s-service-account
entity:
  criteria:
  - app_id: aws-iam-example
  driver_inputs:
    values:
      templates:
        init: |
          {{- /*
            .driver.values.resId will have the form: modules.<workloadName>
          */ -}}
          name: {{ index ( .driver.values.resId | splitList "." ) 1 }}-service-account
  
        manifests: |
          service-account.yaml:
            location: namespace
            data:
              apiVersion: v1
              kind: ServiceAccount
              metadata:
                name: {{ .init.name }}
              
        outputs: |
          name: {{ .init.name }}
  
      resId: ${context.res.id}
  driver_type: humanitec/template
  name: aws-iam-example-k8s-service-account
  provision:
    aws-role:
      match_dependents: true
  type: k8s-service-account